version: "3.3"

services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: mailing_backend
    volumes:
      - .:/code
    command: ./docker_commands.sh
    env_file:
      - ./mailing/.env
    restart: unless-stopped
    ports:
      - "8080:8080"
